// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfnxiyxneanvxyfmswbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbnhpeXhuZWFudnh5Zm1zd2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDYzOTksImV4cCI6MjA1OTg4MjM5OX0.umDcrBiakmTQWNuPAd5kpWVRp6yUvEUjRptdo2U_fqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);